### ISSUE TITLE
Feature-Request

### ISSUE THREAD

**Issue by Lacroze** [kruvazekonyak/AltoHttp#10]
The possibility to download files from restricted areas would be great.
Something like 

` WebClient.Credentials = new NetworkCredential("user", "D8$pass");`

**Comment by aalitor** [comment]
Hi @Lacroze ,

AltoHttp provides to edit request before sending. You can use BeforeSendingRequest event to edit and add credentials. If it doesnt work let me know please

```
downloader_BeforeSendingRequest(object sender, BeforeSendingRequestEventArgs e)
{
     var req=(HttpWebRequest)e.Request;
     req.Credentials = new NetworkCredentials("user","password");
}

```
