### ISSUE TITLE
How to stop the download process ?

### ISSUE THREAD

**Issue by GDETIENNE** [kruvazekonyak/AltoHttp#12]
Hello,

As already said by  Coinmaster123456, your class does not implement a stop/exit method...

Is there a workaround ?

Thank you !

**Comment by Coinners** [comment]
Also WPF Apps won't exit unless you kill them, because of the missing stop/exit method. I simply pause and then set the downloader to null if I don't need it anymore (I know that this is a very bad strategy but I didn't find any way around)

**Comment by aalitor** [comment]
Hi @GDETIENNE ,

Added a stop and reset method in newer version
