### ISSUE TITLE
Null Exception

### ISSUE THREAD

**Issue by Coinners** [kruvazekonyak/AltoHttp#13]
If RemoteFileInfo.Get(Url, BeforeSendingRequest, AfterGettingResponse); gets a timeout, Info is null here (The catch block of your Process function):
![image](https://user-images.githubusercontent.com/70707774/113862620-ed82bc00-97a8-11eb-8250-e6cc8020c003.png)

**Comment by aalitor** [comment]
Hi @Coinmaster123456 ,

Null check condition added. Thanks for the feedback
