### ISSUE TITLE
Problems. The requested security protocol is not supported?

### ISSUE THREAD

**Issue by Reaper-97** [kruvazekonyak/AltoHttp#14]
Does anyone know how to fix this problem? It happens every time i start the download.
Added a picture of my sample test code below.

![devenv_yu72ovOTIs](https://user-images.githubusercontent.com/78819246/118412442-4132d000-b69a-11eb-8719-2514288143da.png)

**Comment by aalitor** [comment]
Hi @Reaper-97 ,

Can you share your source url please?

**Comment by kedarshet** [comment]
I am facing same problem..
![image](https://user-images.githubusercontent.com/62643927/119990695-44a55000-bfe6-11eb-9eb6-8d86c60fb48b.png)

**Comment by aalitor** [comment]
Hi @kedarshet 

I need your url to test and see the problem
