### ISSUE TITLE
Ability to really resume file (not one thats been "paused")

### ISSUE THREAD

**Issue by TrendyTim** [kruvazekonyak/AltoHttp#4]
It would be nice if either
a) AltoHttp detected the file already exists and get the number of bytes and automatically resumes (it wouldn't hurt to roll back a few bytes, like some download managers do)
b) A method created to resume a file that was already present (as best i can tell, i can safely hack it with a reflection call to the private download method, but its s little ugly).

**Comment by aalitor** [comment]
Hi TrendyTim

It has been long time since you posted this request, sorry for late response. AltoHttp was rewritten and simplified, added some features and one of them is your request. Check if you are still interested.

**Comment by aalitor** [comment]
done

**Comment by aalitor** [comment]
done

**Comment by jorensanbar** [comment]
downloader = new HttpDownloader(url, defaultSavePath);

var fileInfo = new FileInfo(defaultSavePath);

if (fileInfo.Exists)
downloader.Resume();
else
downloader.Start();

Error: "Resume Only when not downloading."
