### ISSUE TITLE
Where is the demo Application Code ?

### ISSUE THREAD

**Issue by Camelxx** [kruvazekonyak/AltoHttp#7]
Hi First of all very nice package i like to see the code for the demo application
![image](https://user-images.githubusercontent.com/44997021/91526654-6f9e2e80-e904-11ea-8f25-41bdcf84873d.png)

**Comment by hlm750908** [comment]
using AltoHttp;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace AltoHttpDemo
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }
        void ok(string str)
        {
            button1.Text = str;
        }

        void setNow(int i)
        {
            progressBar1.Value = i;

        }
        private void Form1_Load(object sender, EventArgs e)
        {

        }

        private void button1_Click(object sender, EventArgs e)
        {
            Thread th1 = new Thread(new ThreadStart(go));
            th1.Start();
        }

        private void go()
        {
            string url = "http://47.101.1 :8088/softupdate/updatetest/d78cef254b0beac670cc02594323d7ff.rar";
            string finalFilePath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop) + "\\" + Path.GetFileName(url);
           // string directoryForChunks = "c:\\temp";
            HttpDownloader dd = new HttpDownloader(url, finalFilePath);
            dd.DownloadCompleted += Dd_DownloadCompleted;
            dd.ProgressChanged += Dd_ProgressChanged;
            dd.Start();
        }

        private void Dd_ProgressChanged(object sender, AltoHttp.ProgressChangedEventArgs e)
        {
            progressBar1.Invoke(new Action<int>(setNow), (int)e.Progress);
        }

        private void Dd_DownloadCompleted(object sender, EventArgs e)
        {
            button1.Invoke(new Action<string>(ok), "Download Completed");
        }
    }
}

**Comment by aalitor** [comment]
Hi @Camelxx ,

I have added an embedded Demo Application in the code with newly added features
